### ISSUE TITLE
Error compiling on CentOS 6.8 i686

### ISSUE THREAD

**Issue by tericsson** [xnsystems/kpcre#26]
Same problem as described before but this time only on 32-bit CentOS 6.8
Compiling on x64 CentOS 6.8 with same setup works flawlessly.
Would be great if this problem could be fixed. Excellent module.

WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_pcre.ko needs unknown symbol pcre2_jit_stack_free_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_pcre.ko needs unknown symbol pcre2_substring_get_bynumber_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_pcre.ko needs unknown symbol pcre2_substring_free_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_pcre.ko needs unknown symbol pcre2_match_context_free_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_pcre.ko needs unknown symbol pcre2_compile_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_pcre.ko needs unknown symbol pcre2_match_context_create_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_pcre.ko needs unknown symbol pcre2_get_ovector_pointer_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_pcre.ko needs unknown symbol pcre2_jit_stack_assign_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_pcre.ko needs unknown symbol pcre2_match_data_free_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_pcre.ko needs unknown symbol pcre2_match_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_pcre.ko needs unknown symbol pcre2_jit_compile_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_pcre.ko needs unknown symbol pcre2_match_data_create_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_pcre.ko needs unknown symbol pcre2_code_free_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_pcre.ko needs unknown symbol pcre2_jit_stack_create_8
make[2]: Leaving directory `/usr/src/kernels/2.6.32-642.15.1.el6.i686'
depmod -a;
make[1]: Leaving directory `/root/kpcre/ts_pcre'
make[1]: Entering directory `/root/kpcre/ts_regex'
make -C /lib/modules/2.6.32-642.15.1.el6.i686/build M=$PWD modules_install;
make[2]: Entering directory `/usr/src/kernels/2.6.32-642.15.1.el6.i686'
  INSTALL /root/kpcre/ts_regex/ts_regex.ko
  DEPMOD  2.6.32-642.15.1.el6.i686
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_regex.ko needs unknown symbol pcre2_substring_get_bynumber_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_regex.ko needs unknown symbol pcre2_substring_free_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_regex.ko needs unknown symbol pcre2_compile_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_regex.ko needs unknown symbol regcomp
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_regex.ko needs unknown symbol regexec
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_regex.ko needs unknown symbol pcre2_match_data_free_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_regex.ko needs unknown symbol pcre2_match_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_regex.ko needs unknown symbol pcre2_match_data_create_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_regex.ko needs unknown symbol pcre2_code_free_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_regex.ko needs unknown symbol regfree
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_pcre.ko needs unknown symbol pcre2_jit_stack_free_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_pcre.ko needs unknown symbol pcre2_substring_get_bynumber_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_pcre.ko needs unknown symbol pcre2_substring_free_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_pcre.ko needs unknown symbol pcre2_match_context_free_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_pcre.ko needs unknown symbol pcre2_compile_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_pcre.ko needs unknown symbol pcre2_match_context_create_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_pcre.ko needs unknown symbol pcre2_get_ovector_pointer_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_pcre.ko needs unknown symbol pcre2_jit_stack_assign_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_pcre.ko needs unknown symbol pcre2_match_data_free_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_pcre.ko needs unknown symbol pcre2_match_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_pcre.ko needs unknown symbol pcre2_jit_compile_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_pcre.ko needs unknown symbol pcre2_match_data_create_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_pcre.ko needs unknown symbol pcre2_code_free_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_pcre.ko needs unknown symbol pcre2_jit_stack_create_8
make[2]: Leaving directory `/usr/src/kernels/2.6.32-642.15.1.el6.i686'
depmod -a;
make[1]: Leaving directory `/root/kpcre/ts_regex'

Problems seems to be segmentation fault when compiling pcre2_jit_compile.c. 
Tried on both Intel and AMD CPUs with same result.

  CC [M]  /root/kpcre/pcre2/pcre2_jit_compile.o
/bin/sh: line 1:  3950 Done(2)                 gcc -E -D__GENKSYMS__ -Wp,-MD,/root/kpcre/pcre2/.pcre2_jit_compile.o.d -nostdinc -isystem /usr/lib/gcc/i686-redhat-linux/4.4.7/include -Iinclude -I/usr/src/kernels/2.6.32-642.15.1.el6.i686/include/uapi -I/usr/src/kernels/2.6.32-642.15.1.el6.i686/arch/x86/include -Iarch/include/generated -Iinclude -include /usr/src/kernels/2.6.32-642.15.1.el6.i686/include/linux/kconfig.h -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -O2 -m32 -msoft-float -mregparm=3 -freg-struct-return -mpreferred-stack-boundary=2 -march=i686 -mtune=generic -Wa,-mtune=generic32 -ffreestanding -fstack-protector -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_AVX=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -Wframe-larger-than=1024 -Wno-unused-but-set-variable -fomit-frame-pointer -g -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fno-dwarf2-cfi-asm -fconserve-stack -O2 -s -I/root/kpcre/pcre2/../libc/ -DHAVE_CONFIG_H -DPCRE2_CODE_UNIT_WIDTH=8 -DMODULE -D"KBUILD_STR(s)=#s" -D"KBUILD_BASENAME=KBUILD_STR(pcre2_jit_compile)" -D"KBUILD_MODNAME=KBUILD_STR(libpcre2_8)" -D"DEBUG_HASH=31" -D"DEBUG_HASH2=1" /root/kpcre/pcre2/pcre2_jit_compile.c
      3951 Segmentation fault      | scripts/genksyms/genksyms -a i386 -r /dev/null > /root/kpcre/pcre2/.tmp_pcre2_jit_compile.ver

**Comment by tericsson** [comment]
Excellent, thank you.

Still get the warnings below but the module compiles and after testing it appears
to work exactly as expected.

WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_pcre.ko needs unknown symbol pcre2_jit_stack_free_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_pcre.ko needs unknown symbol pcre2_substring_get_bynumber_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_pcre.ko needs unknown symbol pcre2_substring_free_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_pcre.ko needs unknown symbol pcre2_match_context_free_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_pcre.ko needs unknown symbol pcre2_compile_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_pcre.ko needs unknown symbol pcre2_match_context_create_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_pcre.ko needs unknown symbol pcre2_get_ovector_pointer_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_pcre.ko needs unknown symbol pcre2_jit_stack_assign_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_pcre.ko needs unknown symbol pcre2_match_data_free_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_pcre.ko needs unknown symbol pcre2_match_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_pcre.ko needs unknown symbol pcre2_jit_compile_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_pcre.ko needs unknown symbol pcre2_match_data_create_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_pcre.ko needs unknown symbol pcre2_code_free_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_pcre.ko needs unknown symbol pcre2_jit_stack_create_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_regex.ko needs unknown symbol pcre2_substring_get_bynumber_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_regex.ko needs unknown symbol pcre2_substring_free_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_regex.ko needs unknown symbol pcre2_compile_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_regex.ko needs unknown symbol regcomp
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_regex.ko needs unknown symbol regexec
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_regex.ko needs unknown symbol pcre2_match_data_free_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_regex.ko needs unknown symbol pcre2_match_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_regex.ko needs unknown symbol pcre2_match_data_create_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_regex.ko needs unknown symbol pcre2_code_free_8
WARNING: /lib/modules/2.6.32-642.15.1.el6.i686/extra/ts_regex.ko needs unknown symbol regfree

**Comment by smcho-kr** [comment]
Those warnings showed probably due to the previously installed modules.
If you build it again, they won't appear.
