### ISSUE TITLE
dot as dot

### ISSUE THREAD

**Issue by ucokkarnadi** [xnsystems/kpcre#32]
Hi there,
many thank's for your code
i was install your code to my linux machine ( ubuntu 16.04 over KVM ) and running but i have 1 issue. where in regex dot not as dot.  i wan to know hot to get dot as dot. i try like this

iptables -A INPUT -m string --string "/\bm[0-9]{1,2}.[a-z]{7}.[a-z]{2,3}(.[a-z]{2,3}|)\b/i" --algo regex -j DROP
or
iptables -A INPUT -m string --string "/\bm[0-9]{1,2}\.[a-z]{7}\.[a-z]{2,3}(\.[a-z]{2,3}|)\b/i" --algo regex -j DROP
or
iptables -A INPUT -m string --string "/\bm[0-9]{1,2}\.[a-z]{7}\.[a-z]{2,3}(\.[a-z]{2,3}|)\b/si" --algo regex -j DROP

but no luck. it's dot still as any character

i implement it to block dns request like this m12.aaaaaaz.com and success. but when dns request like this m12daaaaaazdcom.com or m12daaaaaaz.com blocked too.

can you tell me how to make dot as dot in KPCRE

sorry if my English so bad.

**Comment by inpos** [comment]
Hi.
Do it with escape "\\."

**Comment by ucokkarnadi** [comment]
i have do with it, and im sorry, i post this message whit \. ( or maybe i forget )
and this is my bash history

`  125  iptables -A INPUT -m string --string "/\bm[0-9]{1,2}.[a-z]{7}.[a-z]{2,3}(.[a-z]{2,3}|)\b/i" --algo regex -j DROP
  127  iptables -D INPUT -m string --string "/\bm[0-9]{1,2}.[a-z]{7}.[a-z]{2,3}(.[a-z]{2,3}|)\b/i" --algo regex -j DROP
  128  iptables -A INPUT -m string --string "/\bm[0-9]{1,2}\.[a-z]{7}\.[a-z]{2,3}(\.[a-z]{2,3}|)\b/i" --algo regex -j DROP
  129  iptables -D INPUT -m string --string "/\bm[0-9]{1,2}\.[a-z]{7}\.[a-z]{2,3}(\.[a-z]{2,3}|)\b/i" --algo regex -j DROP
  135  iptables -A INPUT -m string --string "/\bm[0-9]{1,2}\.[a-z]{7}\.[a-z]{2,3}(\.[a-z]{2,3}|)\b/s" --algo regex -j DROP
  136  iptables -D INPUT -m string --string "/\bm[0-9]{1,2}\.[a-z]{7}\.[a-z]{2,3}(\.[a-z]{2,3}|)\b/s" --algo regex -j DROP
  137  iptables -A INPUT -m string --string "/\bm[0-9]{1,2}\.[a-z]{7}\.[a-z]{2,3}(\.[a-z]{2,3}|)/s" --algo regex -j DROP
  138  iptables -D INPUT -m string --string "/\bm[0-9]{1,2}\.[a-z]{7}\.[a-z]{2,3}(\.[a-z]{2,3}|)/s" --algo regex -j DROP
  139  iptables -A INPUT -m string --string "/\bm[0-9]{1,2}.[a-z]{7}.[a-z]{2,3}(.[a-z]{2,3}|)\b/i" --algo regex -j DROP
`

>

**Comment by inpos** [comment]
Try regex with options: smi
Ex.: /regex/smi

**Comment by inpos** [comment]
Another way is try algo pcre and options: smix
Also you can use regex aliases: replace [0-9] with \\d

**Comment by smcho-kr** [comment]
The actual DNS packet has no "."(DOT) characters.
When you send a DNS query for "www.xnsystems.com", the actual DNS query packet contains the byte string " |03|www|09|xnsystems|03|com". the first |03| mean 0x3, which is the length of the following token("www" ).

**Comment by ucokkarnadi** [comment]
hi @smcho-kr , can you give me iptables rule so match with this regex please....

`\bm[0-9]{1,2}\.[a-z]{7}\.[a-z]{2,3}(\.[a-z]{2,3}|)\b`

i need iptables rule with this regex so i can block dns request from malware. just like picture in this link

[https://pbs.twimg.com/media/DTlz0ifVoAAD6-h.jpg:large](url)

thank you so much

**Comment by smcho-kr** [comment]
It's a little tricky problem to give the exact solution because the pattern is affected by the previous partial match result.
However, I think this pattern will do the work in your case.

(m\d?[1-9]|[1-9]0)[^ -~][a-z]+[^ -~][a-z]+

**Comment by ucokkarnadi** [comment]
@smcho-kr thank you very much i'll try it in my development machine to know it work or not
